version: '3'

services:
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=angad1234
      - MYSQL_DATABASE=fastapi
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  api: 
    build: .
    ports:
      - 8000:8000
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_PASSWORD=angad1234
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=root
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - db
volumes:
  db:
    driver: local

  